# Generated by Django 3.1 on 2021-08-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_image',
            name='image',
            field=models.ImageField(null=True, upload_to='new'),
        ),
        migrations.AlterField(
            model_name='old_image',
            name='image',
            field=models.ImageField(null=True, upload_to='old'),
        ),
    ]
