# Generated by Django 3.1 on 2021-08-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_auto_20210807_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_image',
            name='new_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_image', to='detect.new_image'),
        ),
    ]
