# Generated by Django 3.1 on 2021-08-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0003_old_image_new_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_image',
            name='new_image',
        ),
        migrations.AddField(
            model_name='old_image',
            name='new_image_file_name',
            field=models.CharField(max_length=1000000, null=True),
        ),
        migrations.DeleteModel(
            name='New_image',
        ),
    ]
